-- lua/plugins/lspconfig.lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        intelephense = {
          settings = {
            intelephense = {
              stubs = {
                "apache",
                "bcmath",
                "bz2",
                "calendar",
                "com_dotnet",
                "Core",
                "ctype",
                "curl",
                "date",
                "dom",
                "exif",
                "fileinfo",
                "filter",
                "ftp",
                "gd",
                "gettext",
                "hash",
                "iconv",
                "imap",
                "intl",
                "json",
                "libxml",
                "mbstring",
                "mysqli",
                "openssl",
                "pcntl",
                "pcre",
                "PDO",
                "pdo_mysql",
                "pdo_pgsql",
                "pdo_sqlite",
                "Phar",
                "posix",
                "readline",
                "Reflection",
                "session",
                "SimpleXML",
                "soap",
                "sockets",
                "sodium",
                "SPL",
                "standard",
                "tokenizer",
                "xml",
                "xmlreader",
                "xmlwriter",
                "xsl",
                "Zend OPcache",
                "zip",
                "zlib",
                "wordpress",
                "core",
                "json",
              },
              environment = {
                includePaths = { vim.fn.expand("~/.local/share/php-stubs/vendor/php-stubs/wordpress-stubs") },
                phpVersion = "8.0",
              },
            },
          },
        },
      },
    },
  },
}
